
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=false
sudo nmcli d wifi connect "xmcxtlt" password "31415926" ifname p2p0
sudo nmcli d wifi connect "wifi@dr.cn_5G" password "We2best1" ifname p2p0
[device]
wifi.scan-rand-mac-address=no

[keyfile]
unmanaged-devices=interface-name:p2p0,interface-name:p2p-dev-wlan0,interface-name:p2p-dev-p2p0
